
CREATE TYPE "Role" AS ENUM ('ADMIN', 'TEACHER', 'STUDENT');
CREATE TYPE "AccountRole" AS ENUM ('OWNER', 'ADMIN', 'EDITOR', 'VIEWER');
CREATE TYPE "ProjectStatus" AS ENUM ('DRAFT', 'PLANNING', 'IN_PROGRESS', 'IN_REVIEW', 'LAUNCHED', 'PAUSED', 'ARCHIVED');
CREATE TYPE "DeliverableStatus" AS ENUM ('PENDING', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETE', 'BLOCKED');
CREATE TYPE "ActivityType" AS ENUM ('PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_STATUS_CHANGED', 'DELIVERABLE_CREATED', 'DELIVERABLE_UPDATED', 'DELIVERABLE_STATUS_CHANGED', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'COMMENT_POSTED', 'FILE_UPLOADED', 'BILLING_EVENT', 'AUTH_LOGIN', 'AUTH_2FA_VERIFIED', 'AUTH_PASSWORD_RESET', 'AUTH_EMAIL_VERIFIED');
CREATE TYPE "TwoFactorMethod" AS ENUM ('TOTP', 'EMAIL_OTP', 'RECOVERY_CODE');
CREATE TYPE "OtpPurpose" AS ENUM ('EMAIL_VERIFY', 'PASSWORD_RESET', 'TWO_FACTOR_EMAIL');
CREATE TYPE "LegalDocumentType" AS ENUM ('PRIVACY_POLICY', 'TERMS_OF_SERVICE', 'COOKIE_POLICY', 'ACCEPTABLE_USE', 'SERVICE_POLICY');
CREATE TYPE "LegalDocumentStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "ReferralSourceType" AS ENUM ('DIRECT', 'ORGANIC_SEARCH', 'PAID_AD', 'SOCIAL', 'REFERRAL', 'EMAIL_CAMPAIGN', 'OTHER');
CREATE TYPE "OnboardingStatus" AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED');
CREATE TYPE "ProjectHealth" AS ENUM ('ON_TRACK', 'AT_RISK', 'BLOCKED');
CREATE TYPE "ProjectPhase" AS ENUM ('DISCOVERY', 'DESIGN', 'BUILD', 'REVIEW', 'LAUNCH', 'MAINTENANCE');
CREATE TYPE "ApprovalStatus" AS ENUM ('PENDING', 'APPROVED', 'CHANGES_REQUESTED', 'EXPIRED', 'CANCELLED');
CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'VOID');
CREATE TYPE "MaintenanceCadence" AS ENUM ('MONTHLY', 'QUARTERLY', 'ANNUAL');
CREATE TYPE "MaintenanceSubscriptionStatus" AS ENUM ('ACTIVE', 'PAUSED', 'CANCELLED', 'EXPIRED');
CREATE TYPE "MaintenanceRequestType" AS ENUM ('UPDATE', 'BUG_FIX', 'CONTENT_EDIT', 'PERFORMANCE', 'SECURITY', 'BACKUP_RESTORE', 'CONSULT');
CREATE TYPE "TicketPriority" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');
CREATE TYPE "TicketStatus" AS ENUM ('OPEN', 'PENDING_CUSTOMER', 'PENDING_STAFF', 'RESOLVED', 'CLOSED');
CREATE TYPE "TicketMessageVisibility" AS ENUM ('CUSTOMER', 'INTERNAL');
CREATE TYPE "NotificationKind" AS ENUM ('PROJECT', 'APPROVAL', 'INVOICE', 'MAINTENANCE', 'SUPPORT', 'SECURITY', 'ACCOUNT');
CREATE TYPE "DataExportStatus" AS ENUM ('QUEUED', 'RUNNING', 'READY', 'FAILED', 'EXPIRED');
CREATE TYPE "CommunicationPreference" AS ENUM ('EMAIL', 'PHONE', 'SLACK', 'TEAMS');
CREATE TYPE "FileAssetStatus" AS ENUM ('PENDING', 'READY', 'SCANNING', 'INFECTED', 'ARCHIVED');
CREATE TYPE "ResolutionCode" AS ENUM ('FIXED', 'WORKAROUND', 'DUPLICATE', 'WONT_FIX', 'CUSTOMER_RESPONDED', 'ESCALATED_TO_ENGINEERING', 'BILLING_ADJUSTMENT', 'OTHER');
CREATE TYPE "CustomerSentiment" AS ENUM ('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'AT_RISK');
CREATE TYPE "AccountStatus" AS ENUM ('ACTIVE', 'AT_RISK', 'CHURNING', 'DORMANT', 'CLOSED');
CREATE TYPE "NoteVisibility" AS ENUM ('INTERNAL_TEAM', 'LEADERSHIP', 'PRIVATE');
CREATE TYPE "SlaSeverity" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'CRITICAL');
CREATE TYPE "AuditEventType" AS ENUM ('TICKET_CREATED', 'TICKET_ASSIGNED', 'TICKET_REASSIGNED', 'TICKET_ESCALATED', 'TICKET_RESOLVED', 'TICKET_CLOSED', 'TICKET_REOPENED', 'MESSAGE_POSTED', 'INTERNAL_NOTE_ADDED', 'PRIORITY_CHANGED', 'STATUS_CHANGED', 'MACRO_APPLIED', 'ARTICLE_PUBLISHED', 'ARTICLE_REVISED', 'CUSTOMER_FLAGGED');
CREATE TYPE "JobRunStatus" AS ENUM ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'PARTIAL');
CREATE TYPE "HelpArticleStatus" AS ENUM ('DRAFT', 'IN_REVIEW', 'PUBLISHED', 'ARCHIVED');
CREATE TABLE "support_assignment" (
CREATE TABLE "internal_note" (
    CONSTRAINT "internal_note_pkey" PRIMARY KEY ("id")
CREATE TABLE "escalation_event" (
    CONSTRAINT "escalation_event_pkey" PRIMARY KEY ("id")
CREATE TABLE "sla_policy" (
    CONSTRAINT "sla_policy_pkey" PRIMARY KEY ("id")
CREATE TABLE "canned_response" (
    CONSTRAINT "canned_response_pkey" PRIMARY KEY ("id")
CREATE TABLE "organization_support_profile" (
    CONSTRAINT "organization_support_profile_pkey" PRIMARY KEY ("id")
CREATE TABLE "customer_activity_log" (
    CONSTRAINT "customer_activity_log_pkey" PRIMARY KEY ("id")
CREATE TABLE "content_revision" (
    CONSTRAINT "content_revision_pkey" PRIMARY KEY ("id")
CREATE TABLE "knowledge_feedback" (
    CONSTRAINT "knowledge_feedback_pkey" PRIMARY KEY ("id")
CREATE TABLE "article_attachment" (
    CONSTRAINT "article_attachment_pkey" PRIMARY KEY ("id")
CREATE TABLE "support_metric_daily" (
    CONSTRAINT "support_metric_daily_pkey" PRIMARY KEY ("id")
CREATE TABLE "audit_log" (
    CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id")
CREATE TABLE "support_job_run" (
    CONSTRAINT "support_job_run_pkey" PRIMARY KEY ("id")



