import { Router } from "express"; import status from "http-status"; import AppError from "../../../errorHelpers/AppError"; import { catchAsync } from "../../../utils/catchAsync";
import { requireAdmin, requirePermission, requireStepUp, recordAudit } from "../admin.policy"; import { prisma } from "../admin.service";
export const systemJobOperations = [["get", "/system/health"], ["get", "/system/jobs"], ["post", "/system/jobs/:id/retry"], ["post", "/system/queues/:name/pause"]] as const;
const router = Router(); router.use(requireAdmin);
router.get("/system/health", requirePermission("system-jobs.read"), catchAsync(async (req, res) => { const [queued = 0, failed = 0, running = 0] = await Promise.all(["QUEUED", "FAILED", "RUNNING"].map(s => prisma.adminOutboxJob.count({ where: { status: s } }))); res.json({ data: { status: failed > 0 ? "DEGRADED" : "HEALTHY", queues: { queued, running, failed }, checkedAt: new Date().toISOString() }, requestId: req.id }); }));
router.get("/system/jobs", requirePermission("system-jobs.read"), catchAsync(async (req, res) => { const page = Math.max(1, Number(req.query.page ?? 1)); const pageSize = Math.min(100, Math.max(1, Number(req.query.pageSize ?? 25))); const [data, total] = await prisma.$transaction([prisma.adminOutboxJob.findMany({ orderBy: { createdAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize }), prisma.adminOutboxJob.count()]); res.json({ data, meta: { page, pageSize, total, totalPages: Math.ceil(total / pageSize), requestId: req.id } }); }));
router.post("/system/jobs/:id/retry", requirePermission("system-jobs.write"), catchAsync(async (req, res) => { const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id; const current = id ? await prisma.adminOutboxJob.findUnique({ where: { id } }) : null; if (!current) throw new AppError(status.NOT_FOUND, "Job not found.", { code: "NOT_FOUND" }); const data = await prisma.adminOutboxJob.update({ where: { id: current.id }, data: { status: "QUEUED", failedAt: null, errorCode: null, scheduledAt: new Date(), attempts: { increment: 1 } } }); res.json({ data, requestId: req.id }); }));
router.post("/system/queues/:name/pause", requirePermission("system-jobs.write"), requireStepUp(), catchAsync(async (req, res) => { const paused = req.body?.paused !== false; const data = await prisma.$transaction(async tx => { const queue = await tx.adminQueueControl.upsert({ where: { name: String(req.params.name) }, create: { name: String(req.params.name), paused, updatedBy: req.user.userId }, update: { paused, version: { increment: 1 }, updatedBy: req.user.userId } }); await recordAudit({ actorId: req.user.userId, actorRole: req.user.role, action: "system-jobs.queue-control", target: { kind: "queue", id: queue.name }, after: queue, requestId: req.id }, tx); return queue; }); res.json({ data, requestId: req.id }); }));
export const systemJobsRouter = router;
