import { Router } from "express";
import { dashboardRouter } from "./dashboard/dashboard.route.js";
import { leadsRouter } from "./leads/leads.route.js";
import { quotesRouter } from "./quotes/quotes.route.js";
import { customersRouter } from "./customers/customers.route.js";
import { adminProjectsRouter } from "./projects/projects.route.js";
import { catalogRouter } from "./catalog/catalog.route.js";
import { billingRouter } from "./billing/billing.route.js";
import { teamRouter } from "./team/team.route.js";
import { contentRouter } from "./content/content.route.js";
import { analyticsRouter } from "./analytics/analytics.route.js";
import { settingsRouter } from "./settings/settings.route.js";
import { integrationsRouter } from "./integrations/integrations.route.js";
import { notificationsRouter } from "./notifications/notifications.route.js";
import { featureFlagsRouter } from "./feature-flags/feature-flags.route.js";
import { securityRouter } from "./security/security.route.js";
import { auditLogRouter } from "./audit-log/audit-log.route.js";
import { backupsRouter } from "./backups/backups.route.js";
import { systemJobsRouter } from "./system-jobs/system-jobs.route.js";

/** A1-A22 feature routers are mounted here as they are delivered. */
const router = Router();
router.use("/dashboard", dashboardRouter);
router.use("/leads", leadsRouter);
router.use("/quotes", quotesRouter);
router.use("/customers", customersRouter);
router.use("/projects", adminProjectsRouter);
router.use(catalogRouter);
router.use(billingRouter);
router.use(teamRouter);
router.use(contentRouter);
router.use(analyticsRouter);
router.use(settingsRouter);
router.use(integrationsRouter);
router.use(notificationsRouter);
router.use(featureFlagsRouter);
router.use(securityRouter);
router.use(auditLogRouter);
router.use(backupsRouter);
router.use(systemJobsRouter);

export const adminRouter = router;
